"""create assessments table

Revision ID: 1b5f1dcf278b
Revises: 
Create Date: 2026-09-18 11:26:24.323319

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b5f1dcf278b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assessments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('model_version', sa.Text(), server_default='loan-model-v1', nullable=False),
    sa.Column('contract_type', sa.String(length=50), nullable=False),
    sa.Column('gender', sa.String(length=1), nullable=False),
    sa.Column('owns_car', sa.String(length=1), nullable=False),
    sa.Column('owns_realty', sa.String(length=1), nullable=False),
    sa.Column('children_count', sa.Integer(), nullable=False),
    sa.Column('family_members', sa.Integer(), nullable=False),
    sa.Column('family_status', sa.Text(), nullable=False),
    sa.Column('education_type', sa.Text(), nullable=False),
    sa.Column('income_type', sa.Text(), nullable=False),
    sa.Column('occupation_type', sa.Text(), nullable=True),
    sa.Column('housing_type', sa.Text(), nullable=False),
    sa.Column('annual_income', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('credit_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('annuity_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('goods_price', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('age_years', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('employment_years', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('registration_years', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('id_published_years', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('car_age', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('region_population_relative', sa.Numeric(precision=12, scale=8), nullable=True),
    sa.Column('region_rating', sa.Integer(), nullable=True),
    sa.Column('region_rating_city', sa.Integer(), nullable=True),
    sa.Column('external_source_1', sa.Numeric(precision=8, scale=6), nullable=True),
    sa.Column('external_source_2', sa.Numeric(precision=8, scale=6), nullable=True),
    sa.Column('external_source_3', sa.Numeric(precision=8, scale=6), nullable=True),
    sa.Column('default_probability', sa.Numeric(precision=8, scale=6), nullable=False),
    sa.Column('decision_threshold', sa.Numeric(precision=8, scale=6), nullable=False),
    sa.Column('prediction', sa.SmallInteger(), nullable=False),
    sa.Column('decision', sa.Text(), nullable=False),
    sa.CheckConstraint("contract_type IN ('Cash loans', 'Revolving loans')", name='ck_assessments_contract_type'),
    sa.CheckConstraint("decision IN ('DEFAULT RISK', 'NO DEFAULT RISK')", name='ck_assessments_decision'),
    sa.CheckConstraint("gender IN ('M', 'F')", name='ck_assessments_gender'),
    sa.CheckConstraint("owns_car IN ('Y', 'N')", name='ck_assessments_owns_car'),
    sa.CheckConstraint("owns_realty IN ('Y', 'N')", name='ck_assessments_owns_realty'),
    sa.CheckConstraint('age_years >= 0', name='ck_assessments_age_years'),
    sa.CheckConstraint('annual_income >= 0', name='ck_assessments_annual_income'),
    sa.CheckConstraint('annuity_amount >= 0', name='ck_assessments_annuity_amount'),
    sa.CheckConstraint('car_age IS NULL OR car_age >= 0', name='ck_assessments_car_age'),
    sa.CheckConstraint('children_count >= 0', name='ck_assessments_children_count'),
    sa.CheckConstraint('credit_amount >= 0', name='ck_assessments_credit_amount'),
    sa.CheckConstraint('decision_threshold BETWEEN 0 AND 1', name='ck_assessments_decision_threshold'),
    sa.CheckConstraint('default_probability BETWEEN 0 AND 1', name='ck_assessments_default_probability'),
    sa.CheckConstraint('employment_years >= 0', name='ck_assessments_employment_years'),
    sa.CheckConstraint('external_source_1 IS NULL OR external_source_1 BETWEEN 0 AND 1', name='ck_assessments_external_source_1'),
    sa.CheckConstraint('external_source_2 IS NULL OR external_source_2 BETWEEN 0 AND 1', name='ck_assessments_external_source_2'),
    sa.CheckConstraint('external_source_3 IS NULL OR external_source_3 BETWEEN 0 AND 1', name='ck_assessments_external_source_3'),
    sa.CheckConstraint('family_members > 0', name='ck_assessments_family_members'),
    sa.CheckConstraint('goods_price IS NULL OR goods_price >= 0', name='ck_assessments_goods_price'),
    sa.CheckConstraint('id_published_years >= 0', name='ck_assessments_id_published_years'),
    sa.CheckConstraint('prediction IN (0, 1)', name='ck_assessments_prediction'),
    sa.CheckConstraint('region_population_relative IS NULL OR region_population_relative >= 0', name='ck_assessments_region_population_relative'),
    sa.CheckConstraint('region_rating IS NULL OR region_rating BETWEEN 1 AND 3', name='ck_assessments_region_rating'),
    sa.CheckConstraint('region_rating_city IS NULL OR region_rating_city BETWEEN 1 AND 3', name='ck_assessments_region_rating_city'),
    sa.CheckConstraint('registration_years >= 0', name='ck_assessments_registration_years'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_assessments_created_at', 'assessments', [sa.literal_column('created_at DESC')], unique=False)
    op.create_index('idx_assessments_decision_created_at', 'assessments', ['decision', sa.literal_column('created_at DESC')], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_assessments_decision_created_at', table_name='assessments')
    op.drop_index('idx_assessments_created_at', table_name='assessments')
    op.drop_table('assessments')
    # ### end Alembic commands ###
